from sklearn.pipeline import Pipeline
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import GridSearchCV
import math
import pandas
import numpy as np
data = pandas.read_csv('AmesHousing.csv')
data[ 'Total Bsmt SF' ] = data[ 'Total Bsmt SF' ].fillna( 0 )
data[ 'Lot Frontage' ] = data[ 'Lot Frontage' ].fillna( 0 )
data[ 'Mas Vnr Area' ] = data[ 'Mas Vnr Area' ].fillna( 0 )
data2 = pandas.get_dummies(data,columns = ['Neighborhood','Land Contour','Lot Config','Foundation','Exter Qual'])
#corr= data.corr()
#corr.style.background_gradient(cmap = 'coolwarm')
regressor = TransformedTargetRegressor(
    LinearRegression( n_jobs = -1 ), 
    func = np.sqrt, 
    inverse_func = np.square
)
class SelectColumns(BaseEstimator,TransformerMixin):
    def __init__(self,columns):
        self.columns = columns
    def fit(self,xs,xy,**params):
        return self
    def transform(self,xs):
        return xs[self.columns]
#corr= data.corr()
#corr.style.background_gradient(cmap = 'coolwarm')
steps = [
    #('transform_price',PriceTransformer(np.sqrt)),
    ('column_select',SelectColumns(['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood','Exter Qual_Ex','Exter Qual_Fa','Exter Qual_Gd','Exter Qual_TA'],)),
    ('linear_regression',regressor)
]
grid = {
    'column_select__columns': [ 
        [ 'Gr Liv Area' ], 
        [ 'Gr Liv Area', 'Overall Qual' ], 
        [ 'Gr Liv Area', 'Overall Qual', 'Year Built' ],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area',],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide',],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood','Exter Qual_Ex'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood','Exter Qual_Ex','Exter Qual_Fa'],
        #['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood','Exter Qual_Ex','Exter Qual_Fa','Exter Qual_Gd'],
        ['Gr Liv Area','Overall Qual','Year Built','TotRms AbvGrd','Yr Sold','Overall Cond','Total Bsmt SF','Lot Frontage','Lot Area','Year Remod/Add','Mas Vnr Area','Neighborhood_Blmngtn','Neighborhood_Blueste','Neighborhood_BrDale','Neighborhood_BrkSide','Neighborhood_ClearCr','Neighborhood_CollgCr','Neighborhood_Crawfor','Neighborhood_Edwards','Neighborhood_Gilbert','Neighborhood_Greens','Neighborhood_GrnHill','Neighborhood_IDOTRR','Neighborhood_Landmrk','Neighborhood_MeadowV','Neighborhood_Mitchel','Neighborhood_NAmes','Neighborhood_NPkVill','Neighborhood_NWAmes','Neighborhood_NoRidge','Neighborhood_NridgHt','Neighborhood_OldTown','Neighborhood_SWISU','Neighborhood_Sawyer','Neighborhood_SawyerW','Neighborhood_Somerst','Neighborhood_StoneBr','Neighborhood_Timber','Neighborhood_Veenker','Land Contour_Bnk','Land Contour_HLS','Land Contour_Low','Land Contour_Lvl','Lot Config_Corner','Lot Config_CulDSac','Lot Config_FR2','Lot Config_FR3','Lot Config_Inside','Foundation_BrkTil','Foundation_CBlock','Foundation_PConc','Foundation_Slab','Foundation_Stone','Foundation_Wood','Exter Qual_Ex','Exter Qual_Fa','Exter Qual_Gd','Exter Qual_TA'],
        
        #['Gr Liv Area','Overall Qual','Year Built','1st Flr SF','2nd Flr SF','TotRms AbvGrd','Yr Sold','Overall Cond','Mas Vnr Area']
        
    ], 
    'linear_regression': [
        LinearRegression( n_jobs = -1 ),
        TransformedTargetRegressor(
            LinearRegression( n_jobs = -1 ), 
            func = np.sqrt, 
            inverse_func = np.square 
        ), 
        TransformedTargetRegressor(
            LinearRegression( n_jobs = -1 ),
            func = np.cbrt, 
            inverse_func = lambda y: np.power( y, 3 ) ),
        TransformedTargetRegressor(
            LinearRegression( n_jobs = -1 ),
            func = np.log,
            inverse_func = np.exp),
    ] 
}


pipe = Pipeline(steps)

xs = data2.drop(columns = ['SalePrice'])
ys = data2['SalePrice']
train_x,test_x,train_y,test_y = train_test_split(xs,ys,train_size = 0.7)
pipe.fit(xs,ys)
search = GridSearchCV(pipe,grid, scoring = 'r2',n_jobs = -1)
search.fit(xs,ys)
print(search.best_score_)
print(search.best_params_)